* Certain
1. [ ] Multi-machine use - user specifies a machine name; the destination path finally becomes =<destination path>/<machine name>/<source path>/=
2. Progress bar
3. Better configuration format (see below)
4. Check that the output path exists, and create it (with parents) if it does not.
5. Pause/resume rsync jobs (SIGHUP/SIGCONT) - at per-process level and for all jobs (~contrasync-pause-all~/~contrasync-resume-all~)

** Configuration format
1. Rename "destination" to "prefix", to clarify its use; I want the user to only have to specify it once per backup device.

   How about something like...
   #+BEGIN_SRC emacs-lisp
     '((:prefix "/media/user/my-disk/"
        :sources ("~/.emacs.d/"
                  "~/Documents/")))
   #+END_SRC
2. Instead of requiring changes to =contrasync-command-line= to change the path, make a =format=-like way to specify the final destination path.

   Like ="%p/%m/%s"= for "<prefix path>/<machine name>/<source path>".

   Or maybe use a list - ='(prefix machine source)=

   Use that to do it on a per-path basis -
   #+BEGIN_SRC emacs-lisp
     '((:prefix "/media/user/my-disk/"
        :sources
        ("~/.emacs.d/"
         ;; if a string, use a default destination pattern - probably
         ;; (prefix machine source), user-customizable
         "~/Documents/"
         ;; the destination for this one will be "/media/user/my-disk/foo/"
         ("~/foo/" :destination (prefix source)))))
   #+END_SRC
   We define a ~contrasync-default-destination~, which is a pattern specified as a list. The default value is ~'(prefix machine source)~

   =:sources= can be strings or lists. If they are strings, ~contrasync-default-destination~ will be used to construct the destination. In the above example, "~/.emacs.d/" and "~/Documents" will be synced to "/media/user/my-disk/my-machine/home/user/.emacs.d/" and "/media/user/my-disk/my-machine/home/user/Documents/", respectively.

   If an element of =:sources= is a list, we look for a =:destination= and/or an =:arguments=.

   =:destination= overrides ~contrasync-default-destination~. It can be a string, or a function of two arguments - PREFIX and SOURCE.

   Like
   1. Greater flexibility without needing to change =contrasync-command-line-function=
   2. Structures your config, somewhat like =use-package= - :sources are glued to :prefix (but see #2 below)
   3. Can extend with =:arguments LIST= to override =contrasync-arguments=

   Dislike
   1. Will complicate destructuring.
   2. Can't use a source with a different :prefix (but see #2 above)

   We could also do something similar while keeping the alist -
   #+BEGIN_SRC emacs-lisp
     (let* ((disk              "/media/user/my-disk/")
            (disk-machine-name (concat disk "HP ProBook")))
       `(("~/.emacs.d/"           . ,disk-machine-name)
         ("~/Documents/"          . ,disk-machine-name)
         ("~/put-this-elsewhere/" . ,disk)))
   #+END_SRC
   Like
   1. Provides more control to the user, while keeping the implementation complexity down.

   Dislike
   1. User has to deal with quasiquoting/make =list= calls.
   2. Quasiquoting is visually ugly.
   3. We're still implicitly appending the SOURCE path - so they can't say
      : rsync ... ~/foo/bar/ /my-disk/
      or even
      : rsync ... ~/foo/bar/ /my-disk/foo/bar/
      but only
      : rsync ... ~/foo/bar/ /my-disk/home/user/foo/bar/
      * Could remove the implicit appending, but now the common case of "prefix-path/source-path" will either require more repetition than I'd like (using absolute paths for the destination; the prefix will be repeated in each one!), or more setup than I'd like (let-binding the disk path once, let-binding the source path for each source, and =(concat disk source)= for each destination)
   4. Repetition. Note how we're using =disk= in each path, directly or indirectly. With the plist idea, it is used implicitly. And the most common kind of path (=disk-machine-name=) becomes the (user-customizable) default pattern.

Tried going ahead with the plist described above, but it didn't look good to me at all. Working on a new one -

#+BEGIN_SRC emacs-lisp
  (setq contrasync-disk-path "/media/user/kash-sg-2tb/"
        contrasync-source-paths
        `("~/.emacs.d/"
          "~/1-music-notation/"
          "~/Documents/"
          "~/.config/"
          "~/.local/"
          ("~/phone/Nokia 6.1/" ,contrasync-disk-path
                                ,contrasync-machine-name
                                "phone/Nokia 6.1/")))
#+END_SRC

The default destination path is =(concat contrasync-disk-path contrasync-machine-name source)=, e.g. for "~/.emacs.d/" it will be "/media/user/kash-sg-2tb/HP-ProBook-450-G0/home/user/.emacs.d/"

If the source is a list, the first element should be the source path, and all the other elements are passed to `concat' to get the destination path.

Currently, there is no way to run arbitrary Lisp code to generate the output path. No way to refer to the source path, either - but that's easy to add. (Use the symbol `source', we'll replace it before concatenating.)

* Maybe
1. Better default value for =contrasync-max-procs=? Some way to determine the ideal value, maybe using number of CPU cores and/or network bandwidth?
2. Replace ~--delete-after~ with ~--delete~ when accepting changes? The user has (hopefully) already seen the deletions, and the latter is, I seem to remember, faster and less RAM intensive.
3. Throttle rsync CPU/RAM/disk use?
4. Auto resume with idle timer?
